"""removed unique deck name

Revision ID: fa10c6a931ec
Revises: 0eb9608ac9bb
Create Date: 2023-04-08 23:04:10.440819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa10c6a931ec'
down_revision = '0eb9608ac9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_constraint('uq_deck_name', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_deck_name', ['name'])

    # ### end Alembic commands ###
